DROP TABLE ORA_EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE ORA_DEPARTMENTS CASCADE CONSTRAINTS;
DROP TABLE ORA_JOBS CASCADE CONSTRAINTS;
DROP TABLE ORA_LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE ORA_COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE ORA_REGIONS CASCADE CONSTRAINTS;

