--------------------------------------------------------
--  File created - Pazar-Mayýs-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTION_SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "PRODUCTION_SUPPLIERS" 
   (	"SUPPLIERID" NUMBER(*,0), 
	"COMPANYNAME" NVARCHAR2(40), 
	"CONTACTNAME" NVARCHAR2(30), 
	"CONTACTTITLE" NVARCHAR2(30), 
	"ADDRESS" NVARCHAR2(60), 
	"CITY" NVARCHAR2(15), 
	"REGION" NVARCHAR2(15), 
	"POSTALCODE" NVARCHAR2(10), 
	"COUNTRY" NVARCHAR2(15), 
	"PHONE" NVARCHAR2(24), 
	"FAX" NVARCHAR2(24)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRODUCTION_SUPPLIERS
SET DEFINE OFF;
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('1','Supplier SWRXU','Adolphi, Stepha','Purchasing Manager','2345 Gilbert St.','Londo',null,'10023','UK','(171) 456-7890',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('2','Supplier VHQZD','Hance, Jim','Order Administrator','P.O. Box 5678','New Orleans','LA','10013','USA','(100) 555-0111',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('3','Supplier STUAZ','Parovszky, Alfons','Sales Representative','1234 Oxford Rd.','Ann Arbor','MI','10026','USA','(313) 555-0109','(313) 555-0112');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('4','Supplier QOVFD','Balázs, Erzsébet','Marketing Manager','7890 Sekimai Musashino-shi','Tokyo',null,'10011','Japa','(03) 6789-0123',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('5','Supplier EQPNC','Holm, Michael','Export Administrator','Calle del Rosal 4567','Oviedo','Asturias','10029','Spai','(98) 123 45 67',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('6','Supplier QWUSF','Popkova, Darya','Marketing Representative','8901 Setsuko Chuo-ku','Osaka',null,'10028','Japa','(06) 789-0123',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('7','Supplier GQRCV','Ræbild, Jesper','Marketing Manager','5678 Rose St. Moonie Ponds','Melbourne','Victoria','10018','Australia','(03) 123-4567','(03) 456-7890');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('8','Supplier BWGYE','Iallo, Lucio','Sales Representative','9012 King''s Way','Manchester',null,'10021','UK','(161) 567-8901',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('9','Supplier QQYEU','Basalik, Eva','Sales Agent','Kaloadagatan 4567','Göteborg',null,'10022','Swede','031-345 67 89','031-678 90 12');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('10','Supplier UNAHG','Barnett, Dave','Marketing Manager','Av. das Americanas 2345','Sao Paulo',null,'10034','Brazil','(11) 345 6789',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('11','Supplier ZPYVS','Jain, Mukesh','Sales Manager','Tiergartenstraße 3456','Berli',null,'10016','Germany','(010) 3456789',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('12','Supplier SVIYA','Regev, Barak','International Marketing Mgr.','Bogenallee 9012','Frankfurt',null,'10024','Germany','(069) 234567',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('13','Supplier TEGSC','Brehm, Peter','Coordinator Foreign Markets','Frahmredder 3456','Cuxhave',null,'10019','Germany','(04721) 1234','(04721) 2345');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('14','Supplier KEREV','Keil, Kendall','Sales Representative','Viale Dante, 6789','Ravenna',null,'10015','Italy','(0544) 56789','(0544) 34567');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('15','Supplier NZLIF','Sa?as-Szlejter, Karolina','Marketing Manager','Hatlevegen 1234','Sandvika',null,'10025','Norway','(0)9-012345',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('16','Supplier UHZRG','Scholl, Thorste','Regional Account Rep.','8901 - 8th Avenue Suite 210','Bend','OR','10035','USA','(503) 555-0108',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('17','Supplier QZGUF','Kleinerman, Christia','Sales Representative','Brovallavägen 0123','Stockholm',null,'10033','Swede','08-234 56 78',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('18','Supplier LVJUA','Canel, Fabrice','Sales Manager','3456, Rue des Francs-Bourgeois','Paris',null,'10031','France','(1) 90.12.34.56','(1) 01.23.45.67');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('19','Supplier JDNUG','Chapman, Greg','Wholesale Account Agent','Order Processing Dept. 7890 Paul Revere Blvd.','Bosto','MA','10027','USA','(617) 555-0110','(617) 555-0113');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('20','Supplier CIYNM','Köszegi, Emília','Owner','6789 Serangoon Loop, Suite #402','Singapore',null,'10037','Singapore','012-3456',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('21','Supplier XOXZA','Shakespear, Paul','Sales Manager','Lyngbysild Fiskebakken 9012','Lyngby',null,'10012','Denmark','67890123','78901234');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('22','Supplier FNUXM','Skelly, Bonnie L.','Accounting Manager','Verkoop Rijnweg 8901','Zaandam',null,'10014','Netherlands','(12345) 8901','(12345) 5678');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('23','Supplier ELCR','LaMee, Bria','Product Manager','Valtakatu 1234','Lappeenranta',null,'10032','Finland','(953) 78901',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('24','Supplier JNNES','Clark, Molly','Sales Representative','6789 Prince Edward Parade Hunter''s Hill','Sydney','NSW','10030','Australia','(02) 234-5678','(02) 567-8901');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('25','Supplier ERVYZ','Sprenger, Christof','Marketing Manager','7890 Rue St. Laurent','Montréal','Québec','10017','Canada','(514) 456-7890',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('26','Supplier ZWZDM','Cunha, Gonçalo','Order Administrator','Via dei Gelsomini, 5678','Salerno',null,'10020','Italy','(089) 4567890','(089) 4567890');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('27','Supplier ZRYDZ','Leoni, Alessandro','Sales Manager','4567, rue H. Voiro','Montceau',null,'10036','France','89.01.23.45',null);
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('28','Supplier OAVQT','Teper, Jeff','Sales Representative','Bat. B 2345, rue des Alpes','Annecy',null,'10010','France','01.23.45.67','89.01.23.45');
Insert into PRODUCTION_SUPPLIERS (SUPPLIERID,COMPANYNAME,CONTACTNAME,CONTACTTITLE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,FAX) values ('29','Supplier OGLRK','Walters, Rob','Accounting Manager','0123 rue Chasseur','Ste-Hyacinthe','Québec','10009','Canada','(514) 567-890','(514) 678-9012');
--------------------------------------------------------
--  DDL for Index PK_SUPPLIERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SUPPLIERS" ON "PRODUCTION_SUPPLIERS" ("SUPPLIERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTION_SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "PRODUCTION_SUPPLIERS" ADD CONSTRAINT "PK_SUPPLIERS" PRIMARY KEY ("SUPPLIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("CONTACTTITLE" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("CONTACTNAME" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("COMPANYNAME" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_SUPPLIERS" MODIFY ("SUPPLIERID" NOT NULL ENABLE);
