--------------------------------------------------------
--  File created - Pazar-Mayýs-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTION_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "PRODUCTION_CATEGORIES" 
   (	"CATEGORYID" NUMBER(*,0), 
	"CATEGORYNAME" NVARCHAR2(15), 
	"DESCRIPTION" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PRODUCTION_CATEGORIES
SET DEFINE OFF;
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('1','Beverages','Soft drinks, coffees, teas, beers, and ales');
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('2','Condiments','Sweet and savory sauces, relishes, spreads, and seasonings');
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('3','Confections','Desserts, candies, and sweet breads');
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('4','Dairy Products','Cheeses');
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('5','Grains/Cereals','Breads, crackers, pasta, and cereal');
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('6','Meat/Poultry','Prepared meats');
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('7','Produce','Dried fruit and bean curd');
Insert into PRODUCTION_CATEGORIES (CATEGORYID,CATEGORYNAME,DESCRIPTION) values ('8','Seafood','Seaweed and fish');
--------------------------------------------------------
--  DDL for Index PK_CATEGORIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CATEGORIES" ON "PRODUCTION_CATEGORIES" ("CATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORYNAME
--------------------------------------------------------

  CREATE INDEX "CATEGORYNAME" ON "PRODUCTION_CATEGORIES" ("CATEGORYNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTION_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "PRODUCTION_CATEGORIES" ADD CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PRODUCTION_CATEGORIES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_CATEGORIES" MODIFY ("CATEGORYNAME" NOT NULL ENABLE);
  ALTER TABLE "PRODUCTION_CATEGORIES" MODIFY ("CATEGORYID" NOT NULL ENABLE);
