--------------------------------------------------------
--  File created - Pazar-Mayýs-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HR_EMPLOYEES
--------------------------------------------------------

-- Drop TABLE "HR_EMPLOYEES";

  CREATE TABLE "HR_EMPLOYEES" 
   (	"EMPID" NUMBER(*,0), 
	"LASTNAME" NVARCHAR2(20), 
	"FIRSTNAME" NVARCHAR2(10), 
	"TITLE" NVARCHAR2(30), 
	"TITLEOFCOURTESY" NVARCHAR2(25), 
	"BIRTHDATE" DATE, 
	"HIREDATE" DATE, 
	"ADDRESS" NVARCHAR2(60), 
	"CITY" NVARCHAR2(15), 
	"REGION" NVARCHAR2(15), 
	"POSTALCODE" NVARCHAR2(10), 
	"COUNTRY" NVARCHAR2(15), 
	"PHONE" NVARCHAR2(24), 
	"MGRID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR_EMPLOYEES
SET DEFINE OFF;
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('1','Davis','Sara','CEO','Ms.',to_date('08/12/1958','DD/MM/RRRR'),to_date('01/05/2002','DD/MM/RRRR'),'7890 - 20th Ave. E., Apt. 2A','Seattle','WA','10003','USA','(206) 555-0101',null);
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('2','Funk','Do','Vice President, Sales','Dr.',to_date('19/02/1962','DD/MM/RRRR'),to_date('14/08/2002','DD/MM/RRRR'),'9012 W. Capital Way','Tacoma','WA','10001','USA','(206) 555-0100','1');
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('3','Lew','Judy','Sales Manager','Ms.',to_date('30/08/1973','DD/MM/RRRR'),to_date('01/04/2002','DD/MM/RRRR'),'2345 Moss Bay Blvd.','Kirkland','WA','10007','USA','(206) 555-0103','2');
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('4','Peled','Yael','Sales Representative','Mrs.',to_date('19/09/1947','DD/MM/RRRR'),to_date('03/05/2003','DD/MM/RRRR'),'5678 Old Redmond Rd.','Redmond','WA','10009','USA','(206) 555-0104','3');
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('5','Buck','Sve','Sales Manager','Mr.',to_date('04/03/1965','DD/MM/RRRR'),to_date('17/10/2003','DD/MM/RRRR'),'8901 Garrett Hill','London',null,'10004','UK','(71) 234-5678','2');
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('6','Suurs','Paul','Sales Representative','Mr.',to_date('02/07/1973','DD/MM/RRRR'),to_date('17/10/2003','DD/MM/RRRR'),'3456 Coventry House, Miner Rd.','London',null,'10005','UK','(71) 345-6789','5');
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('7','King','Russell','Sales Representative','Mr.',to_date('29/05/1970','DD/MM/RRRR'),to_date('02/01/2004','DD/MM/RRRR'),'6789 Edgeham Hollow, Winchester Way','London',null,'10002','UK','(71) 123-4567','5');
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('8','Camero','Maria','Sales Representative','Ms.',to_date('09/01/1968','DD/MM/RRRR'),to_date('05/03/2004','DD/MM/RRRR'),'4567 - 11th Ave. N.E.','Seattle','WA','10006','USA','(206) 555-0102','3');
Insert into HR_EMPLOYEES (EMPID,LASTNAME,FIRSTNAME,TITLE,TITLEOFCOURTESY,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,POSTALCODE,COUNTRY,PHONE,MGRID) values ('9','Dolgopyatova','Zoya','Sales Representative','Ms.',to_date('27/01/1976','DD/MM/RRRR'),to_date('15/11/2004','DD/MM/RRRR'),'1234 Houndstooth Rd.','London',null,'10008','UK','(71) 456-7890','5');
--------------------------------------------------------
--  DDL for Index PK_EMPLOYEES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_EMPLOYEES" ON "HR_EMPLOYEES" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IXEMP3
--------------------------------------------------------

  CREATE INDEX "IXEMP3" ON "HR_EMPLOYEES" ("COUNTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HR_EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "PK_EMPLOYEES" PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("HIREDATE" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("TITLEOFCOURTESY" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "HR_EMPLOYEES" MODIFY ("EMPID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HR_EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "HR_EMPLOYEES" ADD CONSTRAINT "FK_EMPLOYEES_EMPLOYEES" FOREIGN KEY ("MGRID")
	  REFERENCES "HR_EMPLOYEES" ("EMPID") ENABLE;
